extends: 
  - airbnb
  - plugin:react/recommended
  - plugin:react-native/all
parser: "@babel/eslint-parser"
env:
  jest: true
  react-native/react-native: true
plugins: 
  - react
  - react-native
rules: 
  react/react-in-jsx-scope: off
  react/style-prop-object: off
  react/jsx-filename-extension: 
    - 'error'
    - extensions: 
      - .js
      - .jsx
  no-use-before-define: off
  react/function-component-definition:
    - 1
    - namedComponents: arrow-function
  arrow-body-style: off
  react-native/no-raw-text:
    - 'error'
    - skip:
      - 'Trans'
  react/jsx-props-no-spreading:
    - 'error'
    - exceptions:
      - Button
      - Pressable
  class-methods-use-this: off
