version: '3.9'

services:
  spotifiuby_mobile_app:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./:/opt/spotifiuby-mobile-app:delegated
      - notused:/opt/spotifiuby-mobile-app/node_modules
    healthcheck:
      disable: true

volumes:
  notused:
