export const ADD_NEW_ARTIST = 'ADD_NEW_ARTIST';
export const UPLOAD_DASHBOARD = 'UPLOAD_DASHBOARD';
export const ARTIST_PROFILE = 'ARTIST_PROFILE';
export const SONG_UPLOADER = 'SONG_UPLOADER';
export const ALBUM_CREATOR = 'ALBUM_CREATOR';
export const ALBUM_PROFILE = 'ALBUM_PROFILE';
