name: Spotifiuby CI

on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: ci
      - name: Run lint checker
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - name: Run test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - name: Generate coverage report
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests,uitests
