name: Spotifiuby CI

on: 
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  
jobs:
  test:
    name: Testing and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Installing dependencies
        run: yarn ci
      - name: Run lint checker
        run: yarn lint
      - name: Run test
        run: yarn test
      - name: Generate coverage report
        run: yarn test:coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests,uitests
